
export const timezones = [

	{id: "Pacific/Niue", timeZoneName: "(UTC-11:00) Niue Time"},
	{id: "Pacific/Pago_Pago", timeZoneName: "(UTC-11:00) Samoa Standard Time"},
	{id: "Pacific/Rarotonga", timeZoneName: "(UTC-10:00) Cook Islands Standard Time"},
	{id: "America/Adak", timeZoneName: "(UTC-10:00) Hawaii-Aleutian Standard Time"},
	{id: "Pacific/Tahiti", timeZoneName: "(UTC-10:00) Tahiti Time"},
	{id: "Pacific/Marquesas", timeZoneName: "(UTC-09:30) Marquesas Time"},
	{id: "America/Sitka", timeZoneName: "(UTC-09:00) Alaska Standard Time"},
	{id: "Pacific/Gambier", timeZoneName: "(UTC-09:00) Gambier Time"},
	{id: "America/Vancouver", timeZoneName: "(UTC-08:00) Pacific Standard Time"},
	{id: "Pacific/Pitcairn", timeZoneName: "(UTC-08:00) Pitcairn Time"},
	{id: "America/Mazatlan", timeZoneName: "(UTC-07:00) Mexican Pacific Standard Time"},
	{id: "America/Fort_Nelson", timeZoneName: "(UTC-07:00) Mountain Standard Time"},
	{id: "America/Dawson", timeZoneName: "(UTC-07:00) Pacific Standard Time"},
	{id: "America/Matamoros", timeZoneName: "(UTC-06:00) Central Standard Time"},
	{id: "Pacific/Easter", timeZoneName: "(UTC-06:00) Easter Island Standard Time"},
	{id: "Pacific/Galapagos", timeZoneName: "(UTC-06:00) Galapagos Time"},
	{id: "America/Rio_Branco", timeZoneName: "(UTC-05:00) Acre Standard Time"},
	{id: "America/Bogota", timeZoneName: "(UTC-05:00) Colombia Standard Time"},
	{id: "America/Havana", timeZoneName: "(UTC-05:00) Cuba Standard Time"},
	{id: "America/Nipigon", timeZoneName: "(UTC-05:00) Eastern Standard Time"},
	{id: "America/Guayaquil", timeZoneName: "(UTC-05:00) Ecuador Time"},
	{id: "America/Lima", timeZoneName: "(UTC-05:00) Peru Standard Time"},
	{id: "America/Manaus", timeZoneName: "(UTC-04:00) Amazon Standard Time"},
	{id: "America/Lower_Princes", timeZoneName: "(UTC-04:00) Atlantic Standard Time"},
	{id: "America/La_Paz", timeZoneName: "(UTC-04:00) Bolivia Time"},
	{id: "America/Santiago", timeZoneName: "(UTC-04:00) Chile Standard Time"},
	{id: "America/Guyana", timeZoneName: "(UTC-04:00) Guyana Time"},
	{id: "America/Asuncion", timeZoneName: "(UTC-04:00) Paraguay Standard Time"},
	{id: "America/Caracas", timeZoneName: "(UTC-04:00) Venezuela Time"},
	{id: "America/St_Johns", timeZoneName: "(UTC-03:30) Newfoundland Standard Time"},
	{id: "America/Argentina/Buenos_Aires", timeZoneName: "(UTC-03:00) Argentina Standard Time"},
	{id: "America/Santarem", timeZoneName: "(UTC-03:00) Brasilia Standard Time"},
	{id: "Atlantic/Stanley", timeZoneName: "(UTC-03:00) Falkland Islands Standard Time"},
	{id: "America/Cayenne", timeZoneName: "(UTC-03:00) French Guiana Time"},
	{id: "America/Nuuk", timeZoneName: "(UTC-03:00) GMT"},
	{id: "Antarctica/Palmer", timeZoneName: "(UTC-03:00) GMT-03:00"},
	{id: "Antarctica/Rothera", timeZoneName: "(UTC-03:00) Rothera Time"},
	{id: "America/Miquelon", timeZoneName: "(UTC-03:00) St. Pierre & Miquelon Standard Time"},
	{id: "America/Paramaribo", timeZoneName: "(UTC-03:00) Suriname Time"},
	{id: "America/Montevideo", timeZoneName: "(UTC-03:00) Uruguay Standard Time"},
	{id: "America/Noronha", timeZoneName: "(UTC-02:00) Fernando de Noronha Standard Time"},
	{id: "Atlantic/South_Georgia", timeZoneName: "(UTC-02:00) South Georgia Time"},
	{id: "Atlantic/Azores", timeZoneName: "(UTC-01:00) Azores Standard Time"},
	{id: "Atlantic/Cape_Verde", timeZoneName: "(UTC-01:00) Cape Verde Standard Time"},
	{id: "America/Scoresbysund", timeZoneName: "(UTC-01:00) East Greenland Standard Time"},
	{id: "Europe/London", timeZoneName: "(UTC) Coordinated Universal Time"},
	{id: "Atlantic/Canary", timeZoneName: "(UTC+00:00) Greenwich Mean Time"},
	{id: "Europe/Amsterdam", timeZoneName: "(UTC+00:00) Western European Standard Time"},
	{id: "Africa/El_Aaiun", timeZoneName: "(UTC+01:00) Central European Standard Time"},
	{id: "Europe/Dublin", timeZoneName: "(UTC+01:00) GMT"},
	{id: "Africa/Brazzaville", timeZoneName: "(UTC+01:00) Greenwich Mean Time"},
	{id: "Africa/Blantyre", timeZoneName: "(UTC+01:00) West Africa Standard Time"},
	{id: "Asia/Gaza", timeZoneName: "(UTC+02:00) Central Africa Time"},
	{id: "Asia/Famagusta", timeZoneName: "(UTC+02:00) Eastern European Standard Time"},
	{id: "Asia/Jerusalem", timeZoneName: "(UTC+02:00) GMT+02:00"},
	{id: "Africa/Maseru", timeZoneName: "(UTC+02:00) Israel Standard Time"},
	{id: "Asia/Qatar", timeZoneName: "(UTC+02:00) South Africa Standard Time"},
	{id: "Africa/Asmara", timeZoneName: "(UTC+03:00) Arabian Standard Time"},
	{id: "Europe/Istanbul", timeZoneName: "(UTC+03:00) East Africa Time"},
	{id: "Europe/Minsk", timeZoneName: "(UTC+03:00) GMT+03:00"},
	{id: "Antarctica/Syowa", timeZoneName: "(UTC+03:00) Moscow Standard Time"},
	{id: "Asia/Tehran", timeZoneName: "(UTC+03:00) Syowa Time"},
	{id: "Asia/Yerevan", timeZoneName: "(UTC+03:30) Iran Standard Time"},
	{id: "Asia/Baku", timeZoneName: "(UTC+04:00) Armenia Standard Time"},
	{id: "Europe/Ulyanovsk", timeZoneName: "(UTC+04:00) Azerbaijan Standard Time"},
	{id: "Asia/Tbilisi", timeZoneName: "(UTC+04:00) GMT+04:00"},
	{id: "Asia/Muscat", timeZoneName: "(UTC+04:00) Georgia Standard Time"},
	{id: "Indian/Mauritius", timeZoneName: "(UTC+04:00) Gulf Standard Time"},
	{id: "Indian/Reunion", timeZoneName: "(UTC+04:00) Mauritius Standard Time"},
	{id: "Europe/Samara", timeZoneName: "(UTC+04:00) Réunion Time"},
	{id: "Indian/Mahe", timeZoneName: "(UTC+04:00) Samara Standard Time"},
	{id: "Europe/Volgograd", timeZoneName: "(UTC+04:00) Seychelles Time"},
	{id: "Asia/Kabul", timeZoneName: "(UTC+04:00) Volgograd Standard Time"},
	{id: "Indian/Kerguelen", timeZoneName: "(UTC+04:30) Afghanistan Time"},
	{id: "Indian/Maldives", timeZoneName: "(UTC+05:00) French Southern & Antarctic Time"},
	{id: "Antarctica/Mawson", timeZoneName: "(UTC+05:00) Maldives Time"},
	{id: "Asia/Karachi", timeZoneName: "(UTC+05:00) Mawson Time"},
	{id: "Asia/Dushanbe", timeZoneName: "(UTC+05:00) Pakistan Standard Time"},
	{id: "Asia/Ashgabat", timeZoneName: "(UTC+05:00) Tajikistan Time"},
	{id: "Asia/Samarkand", timeZoneName: "(UTC+05:00) Turkmenistan Standard Time"},
	{id: "Asia/Oral", timeZoneName: "(UTC+05:00) Uzbekistan Standard Time"},
	{id: "Asia/Yekaterinburg", timeZoneName: "(UTC+05:00) West Kazakhstan Time"},
	{id: "Asia/Colombo", timeZoneName: "(UTC+05:00) Yekaterinburg Standard Time"},
	{id: "Asia/Kathmandu", timeZoneName: "(UTC+05:30) India Standard Time"},
	{id: "Asia/Dhaka", timeZoneName: "(UTC+05:45) Nepal Time"},
	{id: "Asia/Thimphu", timeZoneName: "(UTC+06:00) Bangladesh Standard Time"},
	{id: "Asia/Almaty", timeZoneName: "(UTC+06:00) Bhutan Time"},
	{id: "Asia/Urumqi", timeZoneName: "(UTC+06:00) East Kazakhstan Time"},
	{id: "Indian/Chagos", timeZoneName: "(UTC+06:00) GMT+06:00"},
	{id: "Asia/Bishkek", timeZoneName: "(UTC+06:00) Indian Ocean Time"},
	{id: "Asia/Omsk", timeZoneName: "(UTC+06:00) Kyrgyzstan Time"},
	{id: "Antarctica/Vostok", timeZoneName: "(UTC+06:00) Omsk Standard Time"},
	{id: "Indian/Cocos", timeZoneName: "(UTC+06:00) Vostok Time"},
	{id: "Asia/Yangon", timeZoneName: "(UTC+06:30) Cocos Islands Time"},
	{id: "Indian/Christmas", timeZoneName: "(UTC+06:30) Myanmar Time"},
	{id: "Antarctica/Davis", timeZoneName: "(UTC+07:00) Christmas Island Time"},
	{id: "Asia/Tomsk", timeZoneName: "(UTC+07:00) Davis Time"},
	{id: "Asia/Hovd", timeZoneName: "(UTC+07:00) GMT+07:00"},
	{id: "Asia/Vientiane", timeZoneName: "(UTC+07:00) Hovd Standard Time"},
	{id: "Asia/Krasnoyarsk", timeZoneName: "(UTC+07:00) Indochina Time"},
	{id: "Asia/Novosibirsk", timeZoneName: "(UTC+07:00) Krasnoyarsk Standard Time"},
	{id: "Asia/Jakarta", timeZoneName: "(UTC+07:00) Novosibirsk Standard Time"},
	{id: "Australia/Perth", timeZoneName: "(UTC+07:00) Western Indonesia Time"},
	{id: "Asia/Brunei", timeZoneName: "(UTC+08:00) Australian Western Standard Time"},
	{id: "Asia/Makassar", timeZoneName: "(UTC+08:00) Brunei Darussalam Time"},
	{id: "Asia/Macau", timeZoneName: "(UTC+08:00) Central Indonesia Time"},
	{id: "Asia/Beijing", timeZoneName: "(UTC+08:00) China Standard Time"},
	{id: "Asia/Hong_Kong", timeZoneName: "(UTC+08:00) Hong Kong Standard Time"},
	{id: "Asia/Irkutsk", timeZoneName: "(UTC+08:00) Irkutsk Standard Time"},
	{id: "Asia/Kuching", timeZoneName: "(UTC+08:00) Malaysia Time"},
	{id: "Asia/Manila", timeZoneName: "(UTC+08:00) Philippine Standard Time"},
	{id: "Asia/Singapore", timeZoneName: "(UTC+08:00) Singapore Standard Time"},
	{id: "Asia/Taipei", timeZoneName: "(UTC+08:00) Taipei Standard Time"},
	{id: "Asia/Ulaanbaatar", timeZoneName: "(UTC+08:00) Ulaanbaatar Standard Time"},
	{id: "Australia/Eucla", timeZoneName: "(UTC+08:45) Australian Central Western Standard Time"},
	{id: "Asia/Dili", timeZoneName: "(UTC+09:00) East Timor Time"},
	{id: "Asia/Jayapura", timeZoneName: "(UTC+09:00) Eastern Indonesia Time"},
	{id: "Asia/Tokyo", timeZoneName: "(UTC+09:00) Japan Standard Time"},
	{id: "Asia/Pyongyang", timeZoneName: "(UTC+09:00) Korean Standard Time"},
	{id: "Pacific/Palau", timeZoneName: "(UTC+09:00) Palau Time"},
	{id: "Asia/Chita", timeZoneName: "(UTC+09:00) Yakutsk Standard Time"},
	{id: "Australia/Adelaide", timeZoneName: "(UTC+09:30) Australian Central Standard Time"},
	{id: "Australia/Hobart", timeZoneName: "(UTC+10:00) Australian Eastern Standard Time"},
	{id: "Pacific/Saipan", timeZoneName: "(UTC+10:00) Chamorro Standard Time"},
	{id: "Pacific/Chuuk", timeZoneName: "(UTC+10:00) Chuuk Time"},
	{id: "Antarctica/DumontDUrville", timeZoneName: "(UTC+10:00) Dumont-d’Urville Time"},
	{id: "Pacific/Port_Moresby", timeZoneName: "(UTC+10:00) Papua New Guinea Time"},
	{id: "Asia/Ust-Nera", timeZoneName: "(UTC+10:00) Vladivostok Standard Time"},
	{id: "Australia/Lord_Howe", timeZoneName: "(UTC+10:30) Lord Howe Standard Time"},
	{id: "Asia/Srednekolymsk", timeZoneName: "(UTC+11:00) GMT+11:00"},
	{id: "Pacific/Kosrae", timeZoneName: "(UTC+11:00) Kosrae Time"},
	{id: "Antarctica/Macquarie", timeZoneName: "(UTC+11:00) Macquarie Island Time"},
	{id: "Asia/Magadan", timeZoneName: "(UTC+11:00) Magadan Standard Time"},
	{id: "Pacific/Noumea", timeZoneName: "(UTC+11:00) New Caledonia Standard Time"},
	{id: "Pacific/Norfolk", timeZoneName: "(UTC+11:00) Norfolk Island Standard Time"},
	{id: "Pacific/Pohnpei", timeZoneName: "(UTC+11:00) Ponape Time"},
	{id: "Asia/Sakhalin", timeZoneName: "(UTC+11:00) Sakhalin Standard Time"},
	{id: "Pacific/Guadalcanal", timeZoneName: "(UTC+11:00) Solomon Islands Time"},
	{id: "Pacific/Efate", timeZoneName: "(UTC+11:00) Vanuatu Standard Time"},
	{id: "Asia/Anadyr", timeZoneName: "(UTC+12:00) Anadyr Standard Time"},
	{id: "Pacific/Fiji", timeZoneName: "(UTC+12:00) Fiji Standard Time"},
	{id: "Pacific/Tarawa", timeZoneName: "(UTC+12:00) Gilbert Islands Time"},
	{id: "Pacific/Kwajalein", timeZoneName: "(UTC+12:00) Marshall Islands Time"},
	{id: "Pacific/Nauru", timeZoneName: "(UTC+12:00) Nauru Time"},
	{id: "Pacific/Auckland", timeZoneName: "(UTC+12:00) New Zealand Standard Time"},
	{id: "Asia/Kamchatka", timeZoneName: "(UTC+12:00) Petropavlovsk-Kamchatski Standard Time"},
	{id: "Pacific/Funafuti", timeZoneName: "(UTC+12:00) Tuvalu Time"},
	{id: "Pacific/Wake", timeZoneName: "(UTC+12:00) Wake Island Time"},
	{id: "Pacific/Wallis", timeZoneName: "(UTC+12:00) Wallis & Futuna Time"},
	{id: "Pacific/Chatham", timeZoneName: "(UTC+12:45) Chatham Standard Time"},
	{id: "Pacific/Apia", timeZoneName: "(UTC+13:00) Apia Standard Time"},
	{id: "Pacific/Enderbury", timeZoneName: "(UTC+13:00) Phoenix Islands Time"},
	{id: "Pacific/Fakaofo", timeZoneName: "(UTC+13:00) Tokelau Time"},
	{id: "Pacific/Tongatapu", timeZoneName: "(UTC+13:00) Tonga Standard Time"},
	{id: "Pacific/Kiritimati", timeZoneName: "(UTC+14:00) Line Islands Time"}
];
